# Generated by Django 5.2.8 on 2025-12-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(max_length=11)),
                ('nin', models.CharField(max_length=11)),
                ('account_number', models.CharField(max_length=10)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings')], max_length=20)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_accunnt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
