# Generated by Django 5.2.8 on 2025-12-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_number_alter_account_amount'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loan', to='accounts.account')),
            ],
        ),
    ]
